### ISSUE TITLE
Handwire

### ISSUE THREAD

**Issue by matt-vdv** [CharlesLenk/ErgoDox-Case#1]
Hi, I saw this project and thought it was great! It greatly reduces the print time.

However, I have one question. I am intending to handwire my Ergodox, rather than use a PCB. I'm guessing that for this case the switches are normally supported by the PCB, but would it be possible to use the top of the case to support them (like a plate)? Or would they not snap in properly?

**Comment by CharlesLenk** [comment]
Hey, so I missed this years ago, but in case it's still helpful to you (or anyone else who may see this) you probably don't want to hand wire in this case. The switches do click into the plastic fairly solidly and won't feel loose, but the plastic is not very strong on its own and may lead to a somewhat mushy feeling keyboard without the PCB to add extra rigidity.
